# Path to the oh-my-zsh installation.
export ZSH=/home/docker/.oh-my-zsh

# ZSH Theme
ZSH_THEME=$OH_MY_ZSH_THEME

# Plugins
plugins=(symfony2 composer npm node history ant)

# User configuration
export PATH=$PATH:/usr/local/bin
source $ZSH/oh-my-zsh.sh